# -----------------------------------------------------------------------------
# Copyright [2024] [Rampart AI, Inc.]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rampart-agent-daemonset
  namespace: kube-system # WARNING: runs in privileged namespace #
spec:
  selector:
    matchLabels:
      app: rampart-agent
  template:
    metadata:
      labels:
        app: rampart-agent
    spec:
      containers:
      - image: rampartai/rampart-crs:0.0.6 #rampart-crs:latest
        name: rampart-agent-container
        command: ['/bin/sh']
        args: ['-c', 'ls -lia /agent && echo $CLIENT_CERT_PASS && whoami && base64 /agent/client.crt && java -Drampart.trust.pass=$CLIENT_CERT_PASS -jar jars/auditd-sensor.jar'] #java -jar /agent/auditd-sensor.jar
        env:
        - name: CLIENT_CERT_PASS
          valueFrom:
            secretKeyRef:
              name: rampart-crs-clientcert
              key: client.crt.pass
        - name: 'JAVA_TOOL_OPTIONS'
          value: "-Drampart.ignoreServerVersionIncompatibility=true -DSensorControllerConfig.hostname=rampart-kube-test-box -DRuntimeConfig.archType=CrateAuditdSensor -DRuntimeConfig.archId=crate-scenarios -DRuntimeConfig.soaComponentType=AuditdSensor -DRuntimeConfig.soaComponentId=AuditSensor-crate-scenarios -Drampart.coordinate=com.securboration:auditdsensor:1.0 -Drampart.endpoint=https://rampart.securboration.com:24666 -Drampart.trust.path=/agent/client.crt"
        volumeMounts:
          - name: client-cert
            mountPath: /agent/client.crt
            subPath: client.crt
            readOnly: true
          - name: tetragon-log-data
            mountPath: /var/log/crate/tetragon
      volumes: #tetragon logs are host mounted @ /var/run/cilium/tetragon/tetragon.log -> /var/log/crate/tetragon/tetragon.log
        - name: client-cert
          secret:
            secretName: rampart-crs-clientcert
            items:
              - key: client.crt
                path: client.crt
        - name: tetragon-log-data
          hostPath:
            path: /var/run/cilium/tetragon/
            type: DirectoryOrCreate
